//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\GrammarDemo\SimpleLanguage.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleLanguageLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OR=1, AND=2, EQ=3, NEQ=4, GT=5, LT=6, GTEQ=7, LTEQ=8, PLUS=9, MINUS=10, 
		MULT=11, DIV=12, MOD=13, POW=14, NOT=15, SCOL=16, ASSIGN=17, OPAR=18, 
		CPAR=19, OBRACE=20, CBRACE=21, TRUE=22, FALSE=23, NIL=24, IF=25, ELSE=26, 
		WHILE=27, LOG=28, ID=29, INT=30, FLOAT=31, STRING=32, COMMENT=33, SPACE=34, 
		OTHER=35;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"OR", "AND", "EQ", "NEQ", "GT", "LT", "GTEQ", "LTEQ", "PLUS", "MINUS", 
		"MULT", "DIV", "MOD", "POW", "NOT", "SCOL", "ASSIGN", "OPAR", "CPAR", 
		"OBRACE", "CBRACE", "TRUE", "FALSE", "NIL", "IF", "ELSE", "WHILE", "LOG", 
		"ID", "INT", "FLOAT", "STRING", "COMMENT", "SPACE", "OTHER"
	};


	public SimpleLanguageLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SimpleLanguageLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'||'", "'&&'", "'=='", "'!='", "'>'", "'<'", "'>='", "'<='", "'+'", 
		"'-'", "'*'", "'/'", "'%'", "'^'", "'!'", "';'", "'='", "'('", "')'", 
		"'{'", "'}'", "'true'", "'false'", "'nil'", "'if'", "'else'", "'while'", 
		"'log'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OR", "AND", "EQ", "NEQ", "GT", "LT", "GTEQ", "LTEQ", "PLUS", "MINUS", 
		"MULT", "DIV", "MOD", "POW", "NOT", "SCOL", "ASSIGN", "OPAR", "CPAR", 
		"OBRACE", "CBRACE", "TRUE", "FALSE", "NIL", "IF", "ELSE", "WHILE", "LOG", 
		"ID", "INT", "FLOAT", "STRING", "COMMENT", "SPACE", "OTHER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SimpleLanguage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SimpleLanguageLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '%', '\xD4', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\a', '\x1E', '\x9D', 
		'\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', '\xA0', '\v', '\x1E', '\x3', 
		'\x1F', '\x6', '\x1F', '\xA3', '\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', 
		'\xA4', '\x3', ' ', '\x6', ' ', '\xA8', '\n', ' ', '\r', ' ', '\xE', ' ', 
		'\xA9', '\x3', ' ', '\x3', ' ', '\a', ' ', '\xAE', '\n', ' ', '\f', ' ', 
		'\xE', ' ', '\xB1', '\v', ' ', '\x3', ' ', '\x3', ' ', '\x6', ' ', '\xB5', 
		'\n', ' ', '\r', ' ', '\xE', ' ', '\xB6', '\x5', ' ', '\xB9', '\n', ' ', 
		'\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', '\a', '!', '\xBF', '\n', 
		'!', '\f', '!', '\xE', '!', '\xC2', '\v', '!', '\x3', '!', '\x3', '!', 
		'\x3', '\"', '\x3', '\"', '\a', '\"', '\xC8', '\n', '\"', '\f', '\"', 
		'\xE', '\"', '\xCB', '\v', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', 
		'\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x2', '\x2', 
		'%', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', 
		'\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', 
		'\"', '\x43', '#', '\x45', '$', 'G', '%', '\x3', '\x2', '\b', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', 
		'\x5', '\x2', '\f', '\f', '\xF', '\xF', '$', '$', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\xDC', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x3', 'I', '\x3', '\x2', '\x2', '\x2', '\x5', 'L', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'O', '\x3', '\x2', '\x2', '\x2', '\t', 'R', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'U', '\x3', '\x2', '\x2', '\x2', '\r', 
		'W', '\x3', '\x2', '\x2', '\x2', '\xF', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\\', '\x3', '\x2', '\x2', '\x2', '\x13', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x61', '\x3', '\x2', '\x2', '\x2', '\x17', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x65', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'g', '\x3', '\x2', '\x2', '\x2', '\x1D', 'i', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', 'k', '\x3', '\x2', '\x2', '\x2', '!', 'm', '\x3', '\x2', '\x2', 
		'\x2', '#', 'o', '\x3', '\x2', '\x2', '\x2', '%', 'q', '\x3', '\x2', '\x2', 
		'\x2', '\'', 's', '\x3', '\x2', '\x2', '\x2', ')', 'u', '\x3', '\x2', 
		'\x2', '\x2', '+', 'w', '\x3', '\x2', '\x2', '\x2', '-', 'y', '\x3', '\x2', 
		'\x2', '\x2', '/', '~', '\x3', '\x2', '\x2', '\x2', '\x31', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x88', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x37', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\x96', '\x3', '\x2', '\x2', '\x2', ';', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '=', '\xA2', '\x3', '\x2', '\x2', '\x2', '?', '\xB8', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\xBA', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\xC5', '\x3', '\x2', '\x2', '\x2', '\x45', '\xCE', '\x3', '\x2', 
		'\x2', '\x2', 'G', '\xD2', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', 
		'~', '\x2', '\x2', 'J', 'K', '\a', '~', '\x2', '\x2', 'K', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'L', 'M', '\a', '(', '\x2', '\x2', 'M', 'N', '\a', 
		'(', '\x2', '\x2', 'N', '\x6', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 
		'?', '\x2', '\x2', 'P', 'Q', '\a', '?', '\x2', '\x2', 'Q', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'S', '\a', '#', '\x2', '\x2', 'S', 'T', '\a', 
		'?', '\x2', '\x2', 'T', '\n', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', 
		'@', '\x2', '\x2', 'V', '\f', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', 
		'>', '\x2', '\x2', 'X', '\xE', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', 
		'@', '\x2', '\x2', 'Z', '[', '\a', '?', '\x2', '\x2', '[', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\\', ']', '\a', '>', '\x2', '\x2', ']', '^', '\a', 
		'?', '\x2', '\x2', '^', '\x12', '\x3', '\x2', '\x2', '\x2', '_', '`', 
		'\a', '-', '\x2', '\x2', '`', '\x14', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\a', '/', '\x2', '\x2', '\x62', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', ',', '\x2', '\x2', '\x64', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\a', '\x31', '\x2', '\x2', '\x66', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\'', '\x2', '\x2', 
		'h', '\x1C', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '`', '\x2', '\x2', 
		'j', '\x1E', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '#', '\x2', '\x2', 
		'l', ' ', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', '=', '\x2', '\x2', 
		'n', '\"', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', '?', '\x2', '\x2', 
		'p', '$', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\a', '*', '\x2', '\x2', 
		'r', '&', '\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '+', '\x2', '\x2', 
		't', '(', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '}', '\x2', '\x2', 
		'v', '*', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x7F', '\x2', '\x2', 
		'x', ',', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', 'v', '\x2', '\x2', 
		'z', '{', '\a', 't', '\x2', '\x2', '{', '|', '\a', 'w', '\x2', '\x2', 
		'|', '}', '\a', 'g', '\x2', '\x2', '}', '.', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\a', 'h', '\x2', '\x2', '\x7F', '\x80', '\a', '\x63', '\x2', 
		'\x2', '\x80', '\x81', '\a', 'n', '\x2', '\x2', '\x81', '\x82', '\a', 
		'u', '\x2', '\x2', '\x82', '\x83', '\a', 'g', '\x2', '\x2', '\x83', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', 'p', '\x2', '\x2', '\x85', 
		'\x86', '\a', 'k', '\x2', '\x2', '\x86', '\x87', '\a', 'n', '\x2', '\x2', 
		'\x87', '\x32', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 'k', 
		'\x2', '\x2', '\x89', '\x8A', '\a', 'h', '\x2', '\x2', '\x8A', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 'g', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', 'n', '\x2', '\x2', '\x8D', '\x8E', '\a', 'u', '\x2', '\x2', 
		'\x8E', '\x8F', '\a', 'g', '\x2', '\x2', '\x8F', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\a', 'y', '\x2', '\x2', '\x91', '\x92', 
		'\a', 'j', '\x2', '\x2', '\x92', '\x93', '\a', 'k', '\x2', '\x2', '\x93', 
		'\x94', '\a', 'n', '\x2', '\x2', '\x94', '\x95', '\a', 'g', '\x2', '\x2', 
		'\x95', '\x38', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', 'n', 
		'\x2', '\x2', '\x97', '\x98', '\a', 'q', '\x2', '\x2', '\x98', '\x99', 
		'\a', 'i', '\x2', '\x2', '\x99', ':', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9E', '\t', '\x2', '\x2', '\x2', '\x9B', '\x9D', '\t', '\x3', '\x2', 
		'\x2', '\x9C', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA3', '\t', 
		'\x4', '\x2', '\x2', '\xA2', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA8', '\t', '\x4', '\x2', '\x2', '\xA7', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAF', '\a', '\x30', '\x2', '\x2', '\xAC', '\xAE', '\t', '\x4', '\x2', 
		'\x2', '\xAD', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB4', '\a', 
		'\x30', '\x2', '\x2', '\xB3', '\xB5', '\t', '\x4', '\x2', '\x2', '\xB4', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '@', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xC0', '\a', 
		'$', '\x2', '\x2', '\xBB', '\xBF', '\n', '\x5', '\x2', '\x2', '\xBC', 
		'\xBD', '\a', '$', '\x2', '\x2', '\xBD', '\xBF', '\a', '$', '\x2', '\x2', 
		'\xBE', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xBF', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xBE', 
		'\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', '\x2', '\x2', 
		'\xC1', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xC3', '\xC4', '\a', '$', '\x2', '\x2', '\xC4', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\xC5', '\xC9', '\a', '%', '\x2', '\x2', '\xC6', 
		'\xC8', '\n', '\x6', '\x2', '\x2', '\xC7', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\b', '\"', '\x2', '\x2', '\xCD', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\t', '\a', '\x2', '\x2', '\xCF', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\b', '#', '\x2', 
		'\x2', '\xD1', '\x46', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', '\v', 
		'\x2', '\x2', '\x2', '\xD3', 'H', '\x3', '\x2', '\x2', '\x2', '\f', '\x2', 
		'\x9E', '\xA4', '\xA9', '\xAF', '\xB6', '\xB8', '\xBE', '\xC0', '\xC9', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
