//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\GrammarDemo\SimpleLanguage.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class SimpleLanguageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, Def=2, End=3, Return=4, OR=5, AND=6, EQ=7, NEQ=8, GT=9, LT=10, 
		GTEQ=11, LTEQ=12, PLUS=13, MINUS=14, MULT=15, DIV=16, MOD=17, POW=18, 
		NOT=19, SCOL=20, ASSIGN=21, OPAR=22, CPAR=23, OBRACE=24, CBRACE=25, TRUE=26, 
		FALSE=27, NIL=28, IF=29, ELSE=30, WHILE=31, LOG=32, ID=33, INT=34, FLOAT=35, 
		STRING=36, COMMENT=37, SPACE=38, OTHER=39;
	public const int
		RULE_parse = 0, RULE_block = 1, RULE_functionCall = 2, RULE_functionDecl = 3, 
		RULE_idList = 4, RULE_stat = 5, RULE_assignment = 6, RULE_if_stat = 7, 
		RULE_condition_block = 8, RULE_stat_block = 9, RULE_while_stat = 10, RULE_log = 11, 
		RULE_expr = 12, RULE_atom = 13;
	public static readonly string[] ruleNames = {
		"parse", "block", "functionCall", "functionDecl", "idList", "stat", "assignment", 
		"if_stat", "condition_block", "stat_block", "while_stat", "log", "expr", 
		"atom"
	};

	private static readonly string[] _LiteralNames = {
		null, "','", "'def'", "'end'", "'return'", "'||'", "'&&'", "'=='", "'!='", 
		"'>'", "'<'", "'>='", "'<='", "'+'", "'-'", "'*'", "'/'", "'%'", "'^'", 
		"'!'", "';'", "'='", "'('", "')'", "'{'", "'}'", "'true'", "'false'", 
		"'nil'", "'if'", "'else'", "'while'", "'log'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "Def", "End", "Return", "OR", "AND", "EQ", "NEQ", "GT", "LT", 
		"GTEQ", "LTEQ", "PLUS", "MINUS", "MULT", "DIV", "MOD", "POW", "NOT", "SCOL", 
		"ASSIGN", "OPAR", "CPAR", "OBRACE", "CBRACE", "TRUE", "FALSE", "NIL", 
		"IF", "ELSE", "WHILE", "LOG", "ID", "INT", "FLOAT", "STRING", "COMMENT", 
		"SPACE", "OTHER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SimpleLanguage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SimpleLanguageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SimpleLanguageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SimpleLanguageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ParseContext : ParserRuleContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(SimpleLanguageParser.Eof, 0); }
		public ParseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parse; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterParse(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitParse(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParse(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParseContext parse() {
		ParseContext _localctx = new ParseContext(Context, State);
		EnterRule(_localctx, 0, RULE_parse);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; block();
			State = 29; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public StatContext[] stat() {
			return GetRuleContexts<StatContext>();
		}
		public StatContext stat(int i) {
			return GetRuleContext<StatContext>(i);
		}
		public FunctionDeclContext[] functionDecl() {
			return GetRuleContexts<FunctionDeclContext>();
		}
		public FunctionDeclContext functionDecl(int i) {
			return GetRuleContext<FunctionDeclContext>(i);
		}
		public ITerminalNode Return() { return GetToken(SimpleLanguageParser.Return, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(SimpleLanguageParser.SCOL, 0); }
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Def) | (1L << IF) | (1L << WHILE) | (1L << LOG) | (1L << ID) | (1L << OTHER))) != 0)) {
				{
				State = 33;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IF:
				case WHILE:
				case LOG:
				case ID:
				case OTHER:
					{
					State = 31; stat();
					}
					break;
				case Def:
					{
					State = 32; functionDecl();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 37;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 42;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Return) {
				{
				State = 38; Match(Return);
				State = 39; expr(0);
				State = 40; Match(SCOL);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
	 
		public FunctionCallContext() { }
		public virtual void CopyFrom(FunctionCallContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class LogFunctionCallContext : FunctionCallContext {
		public LogContext log() {
			return GetRuleContext<LogContext>(0);
		}
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public LogFunctionCallContext(FunctionCallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterLogFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitLogFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdentifierFunctionCallContext : FunctionCallContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public IdentifierFunctionCallContext(FunctionCallContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIdentifierFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIdentifierFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifierFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 4, RULE_functionCall);
		int _la;
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				_localctx = new IdentifierFunctionCallContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 44; Match(ID);
				State = 45; Match(OPAR);
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << TRUE) | (1L << FALSE) | (1L << NIL) | (1L << ID) | (1L << INT) | (1L << FLOAT) | (1L << STRING))) != 0)) {
					{
					State = 46; expr(0);
					}
				}

				State = 49; Match(CPAR);
				}
				break;
			case LOG:
				_localctx = new LogFunctionCallContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 50; log();
				State = 51; Match(OPAR);
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MINUS) | (1L << NOT) | (1L << OPAR) | (1L << TRUE) | (1L << FALSE) | (1L << NIL) | (1L << ID) | (1L << INT) | (1L << FLOAT) | (1L << STRING))) != 0)) {
					{
					State = 52; expr(0);
					}
				}

				State = 55; Match(CPAR);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclContext : ParserRuleContext {
		public ITerminalNode Def() { return GetToken(SimpleLanguageParser.Def, 0); }
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode End() { return GetToken(SimpleLanguageParser.End, 0); }
		public IdListContext idList() {
			return GetRuleContext<IdListContext>(0);
		}
		public FunctionDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDecl; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterFunctionDecl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitFunctionDecl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDecl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclContext functionDecl() {
		FunctionDeclContext _localctx = new FunctionDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_functionDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59; Match(Def);
			State = 60; Match(ID);
			State = 61; Match(OPAR);
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 62; idList();
				}
			}

			State = 65; Match(CPAR);
			State = 66; block();
			State = 67; Match(End);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdListContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(SimpleLanguageParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(SimpleLanguageParser.ID, i);
		}
		public IdListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idList; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIdList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIdList(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdListContext idList() {
		IdListContext _localctx = new IdListContext(Context, State);
		EnterRule(_localctx, 8, RULE_idList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69; Match(ID);
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 70; Match(T__0);
				State = 71; Match(ID);
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatContext : ParserRuleContext {
		public IToken _OTHER;
		public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public If_statContext if_stat() {
			return GetRuleContext<If_statContext>(0);
		}
		public While_statContext while_stat() {
			return GetRuleContext<While_statContext>(0);
		}
		public LogContext log() {
			return GetRuleContext<LogContext>(0);
		}
		public ITerminalNode OTHER() { return GetToken(SimpleLanguageParser.OTHER, 0); }
		public StatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatContext stat() {
		StatContext _localctx = new StatContext(Context, State);
		EnterRule(_localctx, 10, RULE_stat);
		try {
			State = 83;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 77; assignment();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 78; if_stat();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 79; while_stat();
				}
				break;
			case LOG:
				EnterOuterAlt(_localctx, 4);
				{
				State = 80; log();
				}
				break;
			case OTHER:
				EnterOuterAlt(_localctx, 5);
				{
				State = 81; _localctx._OTHER = Match(OTHER);
				Console.WriteLine("unknown char: " + (_localctx._OTHER!=null?_localctx._OTHER.Text:null));
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(SimpleLanguageParser.ASSIGN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(SimpleLanguageParser.SCOL, 0); }
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 12, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; Match(ID);
			State = 86; Match(ASSIGN);
			State = 87; expr(0);
			State = 88; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_statContext : ParserRuleContext {
		public ITerminalNode[] IF() { return GetTokens(SimpleLanguageParser.IF); }
		public ITerminalNode IF(int i) {
			return GetToken(SimpleLanguageParser.IF, i);
		}
		public Condition_blockContext[] condition_block() {
			return GetRuleContexts<Condition_blockContext>();
		}
		public Condition_blockContext condition_block(int i) {
			return GetRuleContext<Condition_blockContext>(i);
		}
		public ITerminalNode[] ELSE() { return GetTokens(SimpleLanguageParser.ELSE); }
		public ITerminalNode ELSE(int i) {
			return GetToken(SimpleLanguageParser.ELSE, i);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public If_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIf_stat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIf_stat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_statContext if_stat() {
		If_statContext _localctx = new If_statContext(Context, State);
		EnterRule(_localctx, 14, RULE_if_stat);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 90; Match(IF);
			State = 91; condition_block();
			State = 97;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 92; Match(ELSE);
					State = 93; Match(IF);
					State = 94; condition_block();
					}
					} 
				}
				State = 99;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			State = 102;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 100; Match(ELSE);
				State = 101; stat_block();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Condition_blockContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public Condition_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterCondition_block(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitCondition_block(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Condition_blockContext condition_block() {
		Condition_blockContext _localctx = new Condition_blockContext(Context, State);
		EnterRule(_localctx, 16, RULE_condition_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; expr(0);
			State = 105; stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stat_blockContext : ParserRuleContext {
		public ITerminalNode OBRACE() { return GetToken(SimpleLanguageParser.OBRACE, 0); }
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode CBRACE() { return GetToken(SimpleLanguageParser.CBRACE, 0); }
		public StatContext stat() {
			return GetRuleContext<StatContext>(0);
		}
		public Stat_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stat_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStat_block(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStat_block(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStat_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Stat_blockContext stat_block() {
		Stat_blockContext _localctx = new Stat_blockContext(Context, State);
		EnterRule(_localctx, 18, RULE_stat_block);
		try {
			State = 112;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OBRACE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 107; Match(OBRACE);
				State = 108; block();
				State = 109; Match(CBRACE);
				}
				break;
			case IF:
			case WHILE:
			case LOG:
			case ID:
			case OTHER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 111; stat();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_statContext : ParserRuleContext {
		public ITerminalNode WHILE() { return GetToken(SimpleLanguageParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Stat_blockContext stat_block() {
			return GetRuleContext<Stat_blockContext>(0);
		}
		public While_statContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stat; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterWhile_stat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitWhile_stat(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile_stat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public While_statContext while_stat() {
		While_statContext _localctx = new While_statContext(Context, State);
		EnterRule(_localctx, 20, RULE_while_stat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 114; Match(WHILE);
			State = 115; expr(0);
			State = 116; stat_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogContext : ParserRuleContext {
		public ITerminalNode LOG() { return GetToken(SimpleLanguageParser.LOG, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode SCOL() { return GetToken(SimpleLanguageParser.SCOL, 0); }
		public LogContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_log; } }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterLog(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitLog(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLog(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogContext log() {
		LogContext _localctx = new LogContext(Context, State);
		EnterRule(_localctx, 22, RULE_log);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(LOG);
			State = 119; expr(0);
			State = 120; Match(SCOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NotExprContext : ExprContext {
		public ITerminalNode NOT() { return GetToken(SimpleLanguageParser.NOT, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public NotExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNotExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNotExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusExprContext : ExprContext {
		public ITerminalNode MINUS() { return GetToken(SimpleLanguageParser.MINUS, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public UnaryMinusExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterUnaryMinusExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitUnaryMinusExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiplicationExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode MULT() { return GetToken(SimpleLanguageParser.MULT, 0); }
		public ITerminalNode DIV() { return GetToken(SimpleLanguageParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(SimpleLanguageParser.MOD, 0); }
		public MultiplicationExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterMultiplicationExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitMultiplicationExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicationExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AtomExprContext : ExprContext {
		public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAtomExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAtomExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode OR() { return GetToken(SimpleLanguageParser.OR, 0); }
		public OrExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterOrExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitOrExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AdditiveExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode PLUS() { return GetToken(SimpleLanguageParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(SimpleLanguageParser.MINUS, 0); }
		public AdditiveExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAdditiveExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAdditiveExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode POW() { return GetToken(SimpleLanguageParser.POW, 0); }
		public PowExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterPowExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitPowExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPowExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class RelationalExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode LTEQ() { return GetToken(SimpleLanguageParser.LTEQ, 0); }
		public ITerminalNode GTEQ() { return GetToken(SimpleLanguageParser.GTEQ, 0); }
		public ITerminalNode LT() { return GetToken(SimpleLanguageParser.LT, 0); }
		public ITerminalNode GT() { return GetToken(SimpleLanguageParser.GT, 0); }
		public RelationalExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterRelationalExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitRelationalExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EqualityExprContext : ExprContext {
		public IToken op;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode EQ() { return GetToken(SimpleLanguageParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(SimpleLanguageParser.NEQ, 0); }
		public EqualityExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterEqualityExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitEqualityExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualityExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AndExprContext : ExprContext {
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode AND() { return GetToken(SimpleLanguageParser.AND, 0); }
		public AndExprContext(ExprContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case MINUS:
				{
				_localctx = new UnaryMinusExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 123; Match(MINUS);
				State = 124; expr(9);
				}
				break;
			case NOT:
				{
				_localctx = new NotExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 125; Match(NOT);
				State = 126; expr(8);
				}
				break;
			case OPAR:
			case TRUE:
			case FALSE:
			case NIL:
			case ID:
			case INT:
			case FLOAT:
			case STRING:
				{
				_localctx = new AtomExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 127; atom();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 153;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 151;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
					case 1:
						{
						_localctx = new PowExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 130;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 131; Match(POW);
						State = 132; expr(11);
						}
						break;
					case 2:
						{
						_localctx = new MultiplicationExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 133;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 134;
						((MultiplicationExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MULT) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((MultiplicationExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 135; expr(8);
						}
						break;
					case 3:
						{
						_localctx = new AdditiveExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 136;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 137;
						((AdditiveExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((AdditiveExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 138; expr(7);
						}
						break;
					case 4:
						{
						_localctx = new RelationalExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 139;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 140;
						((RelationalExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << LT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
							((RelationalExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 141; expr(6);
						}
						break;
					case 5:
						{
						_localctx = new EqualityExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 142;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 143;
						((EqualityExprContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((EqualityExprContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 144; expr(5);
						}
						break;
					case 6:
						{
						_localctx = new AndExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 145;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 146; Match(AND);
						State = 147; expr(4);
						}
						break;
					case 7:
						{
						_localctx = new OrExprContext(new ExprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 148;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 149; Match(OR);
						State = 150; expr(3);
						}
						break;
					}
					} 
				}
				State = 155;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParExprContext : AtomContext {
		public ITerminalNode OPAR() { return GetToken(SimpleLanguageParser.OPAR, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode CPAR() { return GetToken(SimpleLanguageParser.CPAR, 0); }
		public ParExprContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterParExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitParExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BooleanAtomContext : AtomContext {
		public ITerminalNode TRUE() { return GetToken(SimpleLanguageParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(SimpleLanguageParser.FALSE, 0); }
		public BooleanAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterBooleanAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitBooleanAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBooleanAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdAtomContext : AtomContext {
		public ITerminalNode ID() { return GetToken(SimpleLanguageParser.ID, 0); }
		public IdAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterIdAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitIdAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringAtomContext : AtomContext {
		public ITerminalNode STRING() { return GetToken(SimpleLanguageParser.STRING, 0); }
		public StringAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterStringAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitStringAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NilAtomContext : AtomContext {
		public ITerminalNode NIL() { return GetToken(SimpleLanguageParser.NIL, 0); }
		public NilAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNilAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNilAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNilAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberAtomContext : AtomContext {
		public ITerminalNode INT() { return GetToken(SimpleLanguageParser.INT, 0); }
		public ITerminalNode FLOAT() { return GetToken(SimpleLanguageParser.FLOAT, 0); }
		public NumberAtomContext(AtomContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.EnterNumberAtom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ISimpleLanguageListener typedListener = listener as ISimpleLanguageListener;
			if (typedListener != null) typedListener.ExitNumberAtom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimpleLanguageVisitor<TResult> typedVisitor = visitor as ISimpleLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 26, RULE_atom);
		int _la;
		try {
			State = 165;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPAR:
				_localctx = new ParExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 156; Match(OPAR);
				State = 157; expr(0);
				State = 158; Match(CPAR);
				}
				break;
			case INT:
			case FLOAT:
				_localctx = new NumberAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 160;
				_la = TokenStream.LA(1);
				if ( !(_la==INT || _la==FLOAT) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case TRUE:
			case FALSE:
				_localctx = new BooleanAtomContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 161;
				_la = TokenStream.LA(1);
				if ( !(_la==TRUE || _la==FALSE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case ID:
				_localctx = new IdAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 162; Match(ID);
				}
				break;
			case STRING:
				_localctx = new StringAtomContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 163; Match(STRING);
				}
				break;
			case NIL:
				_localctx = new NilAtomContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 164; Match(NIL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 12: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 10);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		case 5: return Precpred(Context, 3);
		case 6: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ')', '\xAA', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\a', '\x3', '$', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', '\'', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', '-', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x5', '\x4', '\x32', '\n', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '\x38', '\n', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '<', '\n', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '\x42', '\n', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'K', '\n', '\x6', '\f', 
		'\x6', '\xE', '\x6', 'N', '\v', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'V', '\n', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', 
		'\x62', '\n', '\t', '\f', '\t', '\xE', '\t', '\x65', '\v', '\t', '\x3', 
		'\t', '\x3', '\t', '\x5', '\t', 'i', '\n', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x5', '\v', 's', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x5', '\xE', '\x83', '\n', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x9A', 
		'\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x9D', '\v', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '\xA8', '\n', 
		'\xF', '\x3', '\xF', '\x2', '\x3', '\x1A', '\x10', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x2', '\b', '\x3', '\x2', '\x11', '\x13', '\x3', '\x2', '\xF', 
		'\x10', '\x3', '\x2', '\v', '\xE', '\x3', '\x2', '\t', '\n', '\x3', '\x2', 
		'$', '%', '\x3', '\x2', '\x1C', '\x1D', '\x2', '\xB8', '\x2', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x4', '%', '\x3', '\x2', '\x2', '\x2', '\x6', 
		';', '\x3', '\x2', '\x2', '\x2', '\b', '=', '\x3', '\x2', '\x2', '\x2', 
		'\n', 'G', '\x3', '\x2', '\x2', '\x2', '\f', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\xE', 'W', '\x3', '\x2', '\x2', '\x2', '\x10', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\x12', 'j', '\x3', '\x2', '\x2', '\x2', '\x14', 'r', '\x3', 
		'\x2', '\x2', '\x2', '\x16', 't', '\x3', '\x2', '\x2', '\x2', '\x18', 
		'x', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x1F', '\x5', 
		'\x4', '\x3', '\x2', '\x1F', ' ', '\a', '\x2', '\x2', '\x3', ' ', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '!', '$', '\x5', '\f', '\a', '\x2', '\"', 
		'$', '\x5', '\b', '\x5', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', 
		'#', '\"', '\x3', '\x2', '\x2', '\x2', '$', '\'', '\x3', '\x2', '\x2', 
		'\x2', '%', '#', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', 
		'\x2', '&', ',', '\x3', '\x2', '\x2', '\x2', '\'', '%', '\x3', '\x2', 
		'\x2', '\x2', '(', ')', '\a', '\x6', '\x2', '\x2', ')', '*', '\x5', '\x1A', 
		'\xE', '\x2', '*', '+', '\a', '\x16', '\x2', '\x2', '+', '-', '\x3', '\x2', 
		'\x2', '\x2', ',', '(', '\x3', '\x2', '\x2', '\x2', ',', '-', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x5', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 
		'#', '\x2', '\x2', '/', '\x31', '\a', '\x18', '\x2', '\x2', '\x30', '\x32', 
		'\x5', '\x1A', '\xE', '\x2', '\x31', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '\x32', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\x3', '\x2', 
		'\x2', '\x2', '\x33', '<', '\a', '\x19', '\x2', '\x2', '\x34', '\x35', 
		'\x5', '\x18', '\r', '\x2', '\x35', '\x37', '\a', '\x18', '\x2', '\x2', 
		'\x36', '\x38', '\x5', '\x1A', '\xE', '\x2', '\x37', '\x36', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x38', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '\x19', '\x2', '\x2', ':', 
		'<', '\x3', '\x2', '\x2', '\x2', ';', '.', '\x3', '\x2', '\x2', '\x2', 
		';', '\x34', '\x3', '\x2', '\x2', '\x2', '<', '\a', '\x3', '\x2', '\x2', 
		'\x2', '=', '>', '\a', '\x4', '\x2', '\x2', '>', '?', '\a', '#', '\x2', 
		'\x2', '?', '\x41', '\a', '\x18', '\x2', '\x2', '@', '\x42', '\x5', '\n', 
		'\x6', '\x2', '\x41', '@', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\a', '\x19', '\x2', '\x2', '\x44', '\x45', '\x5', '\x4', 
		'\x3', '\x2', '\x45', '\x46', '\a', '\x5', '\x2', '\x2', '\x46', '\t', 
		'\x3', '\x2', '\x2', '\x2', 'G', 'L', '\a', '#', '\x2', '\x2', 'H', 'I', 
		'\a', '\x3', '\x2', '\x2', 'I', 'K', '\a', '#', '\x2', '\x2', 'J', 'H', 
		'\x3', '\x2', '\x2', '\x2', 'K', 'N', '\x3', '\x2', '\x2', '\x2', 'L', 
		'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', '\x2', 
		'M', '\v', '\x3', '\x2', '\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'V', '\x5', '\xE', '\b', '\x2', 'P', 'V', '\x5', '\x10', '\t', 
		'\x2', 'Q', 'V', '\x5', '\x16', '\f', '\x2', 'R', 'V', '\x5', '\x18', 
		'\r', '\x2', 'S', 'T', '\a', ')', '\x2', '\x2', 'T', 'V', '\b', '\a', 
		'\x1', '\x2', 'U', 'O', '\x3', '\x2', '\x2', '\x2', 'U', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'Q', '\x3', '\x2', '\x2', '\x2', 'U', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', '\r', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\a', '#', '\x2', '\x2', 'X', 'Y', '\a', 
		'\x17', '\x2', '\x2', 'Y', 'Z', '\x5', '\x1A', '\xE', '\x2', 'Z', '[', 
		'\a', '\x16', '\x2', '\x2', '[', '\xF', '\x3', '\x2', '\x2', '\x2', '\\', 
		']', '\a', '\x1F', '\x2', '\x2', ']', '\x63', '\x5', '\x12', '\n', '\x2', 
		'^', '_', '\a', ' ', '\x2', '\x2', '_', '`', '\a', '\x1F', '\x2', '\x2', 
		'`', '\x62', '\x5', '\x12', '\n', '\x2', '\x61', '^', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x65', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'h', '\x3', '\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\a', ' ', '\x2', '\x2', 'g', 'i', '\x5', '\x14', 
		'\v', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'h', 'i', '\x3', 
		'\x2', '\x2', '\x2', 'i', '\x11', '\x3', '\x2', '\x2', '\x2', 'j', 'k', 
		'\x5', '\x1A', '\xE', '\x2', 'k', 'l', '\x5', '\x14', '\v', '\x2', 'l', 
		'\x13', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', '\x1A', '\x2', '\x2', 
		'n', 'o', '\x5', '\x4', '\x3', '\x2', 'o', 'p', '\a', '\x1B', '\x2', '\x2', 
		'p', 's', '\x3', '\x2', '\x2', '\x2', 'q', 's', '\x5', '\f', '\a', '\x2', 
		'r', 'm', '\x3', '\x2', '\x2', '\x2', 'r', 'q', '\x3', '\x2', '\x2', '\x2', 
		's', '\x15', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', '!', '\x2', '\x2', 
		'u', 'v', '\x5', '\x1A', '\xE', '\x2', 'v', 'w', '\x5', '\x14', '\v', 
		'\x2', 'w', '\x17', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', '\"', 
		'\x2', '\x2', 'y', 'z', '\x5', '\x1A', '\xE', '\x2', 'z', '{', '\a', '\x16', 
		'\x2', '\x2', '{', '\x19', '\x3', '\x2', '\x2', '\x2', '|', '}', '\b', 
		'\xE', '\x1', '\x2', '}', '~', '\a', '\x10', '\x2', '\x2', '~', '\x83', 
		'\x5', '\x1A', '\xE', '\v', '\x7F', '\x80', '\a', '\x15', '\x2', '\x2', 
		'\x80', '\x83', '\x5', '\x1A', '\xE', '\n', '\x81', '\x83', '\x5', '\x1C', 
		'\xF', '\x2', '\x82', '|', '\x3', '\x2', '\x2', '\x2', '\x82', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', '\x2', 
		'\x83', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\f', '\f', 
		'\x2', '\x2', '\x85', '\x86', '\a', '\x14', '\x2', '\x2', '\x86', '\x9A', 
		'\x5', '\x1A', '\xE', '\r', '\x87', '\x88', '\f', '\t', '\x2', '\x2', 
		'\x88', '\x89', '\t', '\x2', '\x2', '\x2', '\x89', '\x9A', '\x5', '\x1A', 
		'\xE', '\n', '\x8A', '\x8B', '\f', '\b', '\x2', '\x2', '\x8B', '\x8C', 
		'\t', '\x3', '\x2', '\x2', '\x8C', '\x9A', '\x5', '\x1A', '\xE', '\t', 
		'\x8D', '\x8E', '\f', '\a', '\x2', '\x2', '\x8E', '\x8F', '\t', '\x4', 
		'\x2', '\x2', '\x8F', '\x9A', '\x5', '\x1A', '\xE', '\b', '\x90', '\x91', 
		'\f', '\x6', '\x2', '\x2', '\x91', '\x92', '\t', '\x5', '\x2', '\x2', 
		'\x92', '\x9A', '\x5', '\x1A', '\xE', '\a', '\x93', '\x94', '\f', '\x5', 
		'\x2', '\x2', '\x94', '\x95', '\a', '\b', '\x2', '\x2', '\x95', '\x9A', 
		'\x5', '\x1A', '\xE', '\x6', '\x96', '\x97', '\f', '\x4', '\x2', '\x2', 
		'\x97', '\x98', '\a', '\a', '\x2', '\x2', '\x98', '\x9A', '\x5', '\x1A', 
		'\xE', '\x5', '\x99', '\x84', '\x3', '\x2', '\x2', '\x2', '\x99', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x99', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x99', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x99', '\x93', '\x3', '\x2', '\x2', '\x2', '\x99', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x9A', '\x9D', '\x3', '\x2', '\x2', '\x2', 
		'\x9B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', 
		'\x2', '\x2', '\x9C', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '\x18', '\x2', '\x2', 
		'\x9F', '\xA0', '\x5', '\x1A', '\xE', '\x2', '\xA0', '\xA1', '\a', '\x19', 
		'\x2', '\x2', '\xA1', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA8', 
		'\t', '\x6', '\x2', '\x2', '\xA3', '\xA8', '\t', '\a', '\x2', '\x2', '\xA4', 
		'\xA8', '\a', '#', '\x2', '\x2', '\xA5', '\xA8', '\a', '&', '\x2', '\x2', 
		'\xA6', '\xA8', '\a', '\x1E', '\x2', '\x2', '\xA7', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\xA7', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA7', '\xA4', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '\xA8', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x12', '#', 
		'%', ',', '\x31', '\x37', ';', '\x41', 'L', 'U', '\x63', 'h', 'r', '\x82', 
		'\x99', '\x9B', '\xA7',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
